name: Feature Request
description: Suggest a new idea or improvement for the project.
title: "[FEATURE]: "
labels: [enhancement]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: |
        What feature would you like to see added or improved?  
        Please explain what it should do and why it would be useful.
      placeholder: I would like to see…
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature to you?
      options:
        - Must-have
        - Nice to have
        - Low priority
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context or mockups
      description: |
        Optionally, include screenshots, mockups, links, or any extra context that would help.
      placeholder: e.g "Here is concept art I made..." etc.
